name: Build Windows
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get packages
        run: flutter pub get

      - name: Clean build
        run: flutter clean

      - name: Format
        run: dart format .

      - name: Analyze
        run: flutter analyze
        continue-on-error: true

      - name: Build Windows (release)
        run: |
          New-Item -ItemType Directory -Force -Path build_logs | Out-Null
          flutter build windows --release -v *>&1 | Tee-Object -FilePath build_logs\windows_build_verbose.log

      - name: Print context around customers export (for debugging)
        if: always()
        run: |
          $path = "lib/screens/windows/windows_customers_screen.dart"
          if (Test-Path $path) {
            Write-Host "--- Begin $path (line-numbered excerpt) ---"
            $i = 0; Get-Content $path | ForEach-Object { $i++; "{0,5}: {1}" -f $i, $_ } | Select-Object -First 420 -Skip 350
            Write-Host "--- End $path excerpt ---"
          } else {
            Write-Host "File not found: $path"
          }

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-logs
          path: build_logs/

      - name: Upload artifact (Windows exe)
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/
